#!/bin/bash

dirs=("kitty" "nvim" "tmux")

if [ ! -d ~/.tmux/plugins/tpm ]; then
    mkdir -p ~/.tmux/plugins
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

for d in ${dirs[@]}
do
    stow $d
done
