#!/bin/bash

dirs=("amazon" "bin" "kitty" "nvim" "tmux" "zsh")


if [[ $OSTYPE == 'darwin'* ]]; then
    cmds_to_check=("brew" "git" "nvim" "tmux")
else
    cmds_to_check=("fc-cache" "git" "nvim" "tmux")
fi

for cmd in ${cmds_to_check[@]}; do
    hash $cmd 2>/dev/null || \
        { echo >&2 "Please install \"${cmd}\" before proceeding"; exit 1; }
done

echo "Installing fonts..."

if [[ $OSTYPE == 'darwin'* ]]; then
    brew install --cask font-sf-mono-nerd-font
else
    mkdir -p ~/.local/share/fonts
    git clone --depth 1 https://github.com/epk/sf-mono-nerd-font /tmp/nerdfont
    cp /tmp/nerdfont/*.otf ~/.local/share/fonts
    fc-cache -f -v
    rm -rf /tmp/nerdfont
fi

echo "Installing tpm..."

if [ ! -d ~/.tmux/plugins/tpm ]; then
    mkdir -p ~/.tmux/plugins
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

echo "Installing dotfiles..."

for d in ${dirs[@]}; do
    stow $d
done
