#!/bin/bash

dirs=("amazon" "bin" "kitty" "nvim" "tmux" "zsh")

cmds_common=("fzf" "git" "nvim" "rg" "tmux")
cmds_custom=()
if [[ $OSTYPE == 'darwin'* ]]; then
    cmds_custom=("brew")
else
    cmds_custom=("fc-cache")
fi

all_cmds=("${cmds_common[@]}" "${cmds_custom[@]}")

for cmd in ${all_cmds[@]}; do
    hash $cmd 2>/dev/null || \
        { echo >&2 "Please install \"${cmd}\" before proceeding"; exit 1; }
done

echo "Installing fonts..."

if [[ $OSTYPE == 'darwin'* ]]; then
    FONT="font-sf-mono-nerd-font"
    brew list $FONT || brew install --cask $FONT
else
    mkdir -p ~/.local/share/fonts
    git clone --depth 1 https://github.com/epk/sf-mono-nerd-font /tmp/nerdfont
    cp /tmp/nerdfont/*.otf ~/.local/share/fonts
    fc-cache -f -v
    rm -rf /tmp/nerdfont
fi

echo "Installing tpm..."

if [ ! -d ~/.tmux/plugins/tpm ]; then
    mkdir -p ~/.tmux/plugins
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

echo "Installing dotfiles..."

for d in ${dirs[@]}; do
    stow $d
done
